packages:
  - apps/*
  - packages/*

catalog:
  zod: 4.6.5

overrides:
  zod: 4.6.5

patchedDependencies:
  "@rexnow/libs-fetch@0.0.1": patches/@rexnow__libs-fetch@0.0.1.patch
  "@jsr/trakt__api@0.5.4": patches/@jsr__trakt__api@0.5.4.patch

minimumReleaseAgeExclude:
  - "@rexnow/libs@3.1.3"
  - "@rexnow/rslib-plugin@3.1.3"
  - "@rslib/core@1.0.1"
  - "rsbuild-plugin-dts@1.0.1"

allowBuilds:
  esbuild: true
  workerd: true
  "@google/genai": false
  protobufjs: false
