// TODO: 在 pluginRexWidget 类型生成前，通过构建插件从豆瓣 category_tabs 生成此快照。
// ponytail: 本期保留静态数据；豆瓣子榜变化时需手工刷新。
export const SUB_COLLECTIONS = {
  movie_comedy: [
    { id: "ECAYN54KI", name: "近期热门" },
    { id: "movie_comedy", name: "高分经典" },
    { id: "ECVUOUD7A", name: "华语" },
    { id: "ECPQO4BPA", name: "欧洲" },
    { id: "ECKIO6SXI", name: "大陆" },
    { id: "ECGUO62ZA", name: "美国" },
    { id: "ECOYO2QPA", name: "香港" },
    { id: "ECEAOX2BI", name: "台湾" },
    { id: "ECFIOT7JA", name: "日本" },
    { id: "ECOIOVQPY", name: "韩国" },
    { id: "EC6IOYROI", name: "英国" },
    { id: "ECIEOY5UI", name: "法国" },
    { id: "ECFQO5B4A", name: "德国" },
    { id: "ECREOTSEI", name: "意大利" },
    { id: "EC6UO37NQ", name: "西班牙" },
    { id: "ECPMPBHBI", name: "瑞典" },
    { id: "ECTIOYBOY", name: "印度" },
    { id: "ECAIO3EWI", name: "泰国" },
    { id: "ECYUPAHZY", name: "加拿大" },
    { id: "ECKMOXL6Q", name: "澳大利亚" },
    { id: "ECOAOZY7Y", name: "爱尔兰" },
    { id: "ECLYOFOKA", name: "冷门佳作" },
  ],
  movie_love: [
    { id: "ECSAOJFTA", name: "近期热门" },
    { id: "movie_love", name: "高分经典" },
    { id: "ECOIOTUGY", name: "华语" },
    { id: "ECUAOYUCA", name: "欧洲" },
    { id: "EC64OQVEQ", name: "大陆" },
    { id: "EC4EOSAQA", name: "美国" },
    { id: "ECWQOQO4A", name: "台湾" },
    { id: "ECKMOVF3Y", name: "日本" },
    { id: "ECHIOXXIQ", name: "韩国" },
    { id: "ECHAO4AAQ", name: "英国" },
    { id: "ECTAOT7GQ", name: "法国" },
    { id: "ECNIOS7EQ", name: "德国" },
    { id: "EC3UOSWUY", name: "意大利" },
    { id: "ECU4OWMMI", name: "西班牙" },
    { id: "ECCEOUVAA", name: "瑞典" },
    { id: "ECLUOQWVY", name: "印度" },
    { id: "ECYQO7YPQ", name: "泰国" },
    { id: "ECEAOXFIQ", name: "加拿大" },
    { id: "ECOUOXYUA", name: "澳大利亚" },
    { id: "ECJMO2O5Y", name: "爱尔兰" },
    { id: "EC2UOKRRQ", name: "冷门佳作" },
  ],
  movie_action: [
    { id: "ECBUOLQGY", name: "近期热门" },
    { id: "movie_action", name: "高分经典" },
    { id: "EC2YO2M2A", name: "华语" },
    { id: "ECHUOXOUA", name: "欧洲" },
    { id: "ECPMPC7JA", name: "美国" },
    { id: "ECTMO64KY", name: "台湾" },
    { id: "ECBAPBW2Y", name: "日本" },
    { id: "ECWQOU2HI", name: "韩国" },
    { id: "ECCUPDBHQ", name: "英国" },
    { id: "EC5UOWEFY", name: "法国" },
    { id: "EC7AOW57Q", name: "德国" },
    { id: "ECMQO4F2I", name: "印度" },
    { id: "ECUQPDN7Y", name: "加拿大" },
    { id: "EC4QPALEI", name: "澳大利亚" },
    { id: "ECVIOHY6A", name: "冷门佳作" },
  ],
  movie_scifi: [
    { id: "ECZYOJPLI", name: "近期热门" },
    { id: "movie_scifi", name: "高分经典" },
    { id: "ECX4O7JAA", name: "欧洲" },
    { id: "ECDAO6XZI", name: "美国" },
    { id: "ECSYOV6GY", name: "日本" },
    { id: "EC4UOZQ4Y", name: "英国" },
    { id: "EC3MO34NI", name: "法国" },
    { id: "ECOUO2ETY", name: "德国" },
    { id: "ECX4PAGTA", name: "加拿大" },
    { id: "ECTAOXLWQ", name: "澳大利亚" },
    { id: "EC2IOENJA", name: "冷门佳作" },
  ],
  film_genre_31: [
    { id: "EC3UOBDQY", name: "近期热门" },
    { id: "film_genre_31", name: "高分经典" },
    { id: "ECFMOYMKA", name: "华语" },
    { id: "ECLYO57HA", name: "欧洲" },
    { id: "EC4IPDWYI", name: "美国" },
    { id: "ECLYO6JQQ", name: "日本" },
    { id: "ECWUO3RJA", name: "英国" },
    { id: "ECIQPF7NY", name: "法国" },
    { id: "EC3YPB7WQ", name: "加拿大" },
    { id: "ECTUO3I3A", name: "冷门佳作" },
  ],
  film_genre_32: [
    { id: "ECPQOJP5Q", name: "近期热门" },
    { id: "film_genre_32", name: "高分经典" },
    { id: "ECRMOX2JI", name: "华语" },
    { id: "ECUMPB7SA", name: "欧洲" },
    { id: "ECJUO3L7I", name: "美国" },
    { id: "ECV4OU2WA", name: "香港" },
    { id: "ECVYOVDIA", name: "日本" },
    { id: "ECSYOYZWI", name: "韩国" },
    { id: "EC5YPE3OI", name: "英国" },
    { id: "ECQUO7FVQ", name: "法国" },
    { id: "ECZQO7KSQ", name: "德国" },
    { id: "ECVEO7MPI", name: "意大利" },
    { id: "ECAYOVXFA", name: "西班牙" },
    { id: "ECYMPDCTI", name: "加拿大" },
    { id: "ECIMOWR2I", name: "澳大利亚" },
    { id: "ECK4OEBJY", name: "冷门佳作" },
  ],
  film_genre_46: [
    { id: "ECLAN6LHQ", name: "近期热门" },
    { id: "film_genre_46", name: "高分经典" },
    { id: "ECVUO4O4Q", name: "华语" },
    { id: "EC5QO2HUI", name: "欧洲" },
    { id: "ECWAPHUIA", name: "大陆" },
    { id: "ECEAPADKY", name: "美国" },
    { id: "EC3AOZZUY", name: "香港" },
    { id: "ECVUO43DY", name: "日本" },
    { id: "ECGYO2SPA", name: "韩国" },
    { id: "ECVYOZNAI", name: "英国" },
    { id: "ECFEPCR2A", name: "法国" },
    { id: "ECVAPBWRI", name: "德国" },
    { id: "ECRMO4X7I", name: "意大利" },
    { id: "ECPAPDKZA", name: "西班牙" },
    { id: "EC2MPBOOI", name: "加拿大" },
    { id: "ECEMOZ6DI", name: "澳大利亚" },
    { id: "EC7EOG3RI", name: "冷门佳作" },
  ],
  film_genre_33: [
    { id: "ECBUOL2DA", name: "近期热门" },
    { id: "film_genre_33", name: "高分经典" },
    { id: "EC5MPCA7Y", name: "华语" },
    { id: "ECTMPCZTY", name: "欧洲" },
    { id: "ECSYO3JKQ", name: "美国" },
    { id: "ECFUO25PI", name: "日本" },
    { id: "ECTMPDECI", name: "韩国" },
    { id: "ECU4O6QYQ", name: "英国" },
    { id: "ECPMPHOMI", name: "法国" },
    { id: "ECJIPH4JA", name: "德国" },
    { id: "EC2QPBTHY", name: "意大利" },
    { id: "ECLMPAEZY", name: "西班牙" },
    { id: "ECMIPBWCY", name: "瑞典" },
    { id: "ECRQPBSYI", name: "印度" },
    { id: "ECZMPDHQI", name: "加拿大" },
    { id: "EC7QPFMYA", name: "澳大利亚" },
    { id: "ECY4ODRSY", name: "冷门佳作" },
  ],
  film_genre_49: [
    { id: "ECDYOE7WY", name: "近期热门" },
    { id: "film_genre_49", name: "高分经典" },
    { id: "ECAUOWGNQ", name: "华语" },
    { id: "ECW4O3GHY", name: "欧洲" },
    { id: "ECOMON43Q", name: "美国" },
    { id: "ECOUOVT2Q", name: "日本" },
    { id: "ECFUORHLY", name: "英国" },
    { id: "EC5YO53DI", name: "法国" },
    { id: "ECMYOXC2Y", name: "德国" },
    { id: "ECRYO5ULY", name: "加拿大" },
    { id: "ECFIOR3MY", name: "澳大利亚" },
    { id: "ECEMN5MLA", name: "冷门佳作" },
  ],
  film_genre_44: [
    { id: "film_genre_44", name: "高分经典" },
    { id: "ECV4N7YWY", name: "华语" },
    { id: "ECIAOE4OY", name: "欧洲" },
    { id: "ECK4OGBSA", name: "美国" },
    { id: "ECPYOEZNY", name: "香港" },
    { id: "EC54OCODY", name: "日本" },
    { id: "ECMAOINLA", name: "韩国" },
    { id: "ECSEOEISY", name: "英国" },
    { id: "ECUMONVJQ", name: "法国" },
    { id: "ECNQODGKI", name: "德国" },
    { id: "ECL4OLRCY", name: "意大利" },
    { id: "ECBAOKDHQ", name: "冷门佳作" },
  ],
  film_genre_39: [
    { id: "film_genre_39", name: "高分经典" },
    { id: "ECAQO25QI", name: "欧洲" },
    { id: "ECUAOV5NA", name: "美国" },
    { id: "ECFYORPYQ", name: "日本" },
    { id: "ECAQO3LYY", name: "英国" },
    { id: "ECYAORESI", name: "法国" },
    { id: "EC2UOKJFQ", name: "冷门佳作" },
  ],
  film_genre_48: [
    { id: "film_genre_48", name: "高分经典" },
    { id: "EC5MOJAZY", name: "华语" },
    { id: "ECUMOLXQY", name: "欧洲" },
    { id: "ECVIOIPDI", name: "美国" },
    { id: "ECUUOJIFA", name: "香港" },
    { id: "ECEIOJZTQ", name: "日本" },
    { id: "ECDAOLOSI", name: "韩国" },
    { id: "ECRAOGHZY", name: "英国" },
    { id: "EC6QOILRA", name: "法国" },
    { id: "EC4YOCBLQ", name: "德国" },
    { id: "ECCMOLZQA", name: "冷门佳作" },
  ],
  film_genre_34: [
    { id: "ECV4N4FBI", name: "近期热门" },
    { id: "film_genre_34", name: "高分经典" },
    { id: "EC54OE5HA", name: "华语" },
    { id: "ECFAOK5WQ", name: "欧洲" },
    { id: "ECGMORRUY", name: "美国" },
    { id: "EC6QOMMWY", name: "日本" },
    { id: "ECFEOMHIQ", name: "韩国" },
    { id: "ECFUOGJDQ", name: "英国" },
    { id: "ECHIOLPXA", name: "法国" },
    { id: "ECWUOILKA", name: "西班牙" },
    { id: "EC2AOMMKY", name: "泰国" },
    { id: "ECVYODZIA", name: "加拿大" },
    { id: "ECFYOIWBQ", name: "澳大利亚" },
    { id: "ECTMOHSQY", name: "冷门佳作" },
  ],
  film_genre_45: [
    { id: "EC6MOCTVQ", name: "近期热门" },
    { id: "film_genre_45", name: "高分经典" },
    { id: "ECWUOKOLY", name: "华语" },
    { id: "ECUIOKO6I", name: "欧洲" },
    { id: "ECDYONLLI", name: "美国" },
    { id: "ECO4OUYWI", name: "香港" },
    { id: "ECFYOK3AQ", name: "日本" },
    { id: "EC2UOS6AQ", name: "韩国" },
    { id: "ECVIOP57A", name: "英国" },
    { id: "EC6UOQ3TY", name: "法国" },
    { id: "ECV4OGCIA", name: "德国" },
    { id: "ECYUOU5TA", name: "意大利" },
    { id: "ECGEOIWRA", name: "冷门佳作" },
    { id: "ECF4OMYDQ", name: "俄罗斯" },
  ],
  film_genre_43: [
    { id: "EC3EOHEYY", name: "近期热门" },
    { id: "film_genre_43", name: "高分经典" },
    { id: "ECVYOEEUA", name: "华语" },
    { id: "ECZIOQ6LY", name: "欧洲" },
    { id: "ECE4OHQQY", name: "美国" },
    { id: "ECNMONJTQ", name: "英国" },
    { id: "ECYIOK3PY", name: "法国" },
    { id: "ECAYOFADY", name: "德国" },
    { id: "ECLEOKFFQ", name: "意大利" },
    { id: "ECCUOUMXQ", name: "加拿大" },
    { id: "ECRAODXXI", name: "冷门佳作" },
  ],
  film_genre_40: [
    { id: "film_genre_40", name: "高分经典" },
    { id: "EC3QOS5MA", name: "欧洲" },
    { id: "ECYQOXMSA", name: "美国" },
    { id: "ECZMOHQ3Q", name: "冷门佳作" },
  ],
  film_genre_50: [
    { id: "film_genre_50", name: "高分经典" },
    { id: "ECEAOOAHI", name: "华语" },
    { id: "EC6YOLGQQ", name: "大陆" },
    { id: "ECWAOLLZQ", name: "冷门佳作" },
  ],
  film_genre_37: [
    { id: "film_genre_37", name: "高分经典" },
    { id: "ECKQOVFTY", name: "华语" },
    { id: "ECVUONKTI", name: "欧洲" },
    { id: "ECTQOQ6XQ", name: "美国" },
    { id: "ECLUOK4TA", name: "日本" },
    { id: "ECDMOZMVI", name: "韩国" },
    { id: "ECA4OSUNA", name: "英国" },
    { id: "ECDAOW2PY", name: "法国" },
    { id: "ECM4OVMRY", name: "意大利" },
    { id: "ECGYN6NHI", name: "冷门佳作" },
  ],
  natural_disasters: [
    { id: "natural_disasters", name: "高分经典" },
    { id: "EC5IOQ75I", name: "欧洲" },
    { id: "EC4IOWGKA", name: "美国" },
    { id: "ECHMOGZLQ", name: "冷门佳作" },
  ],
  film_genre_47: [
    { id: "film_genre_47", name: "高分经典" },
    { id: "ECM4OWDGI", name: "欧洲" },
    { id: "ECU4ORYVI", name: "美国" },
  ],
  EC74443FY: [
    { id: "EC74443FY", name: "近期热门" },
    { id: "ECT45KVZI", name: "高分经典" },
    { id: "ECVQ47BUI", name: "喜剧" },
    { id: "ECZM5H55I", name: "爱情" },
    { id: "ECIU5AZDA", name: "悬疑" },
    { id: "ECJU5D3PY", name: "家庭" },
    { id: "ECTU453WI", name: "古装" },
    { id: "EC4Q5JNKI", name: "犯罪" },
    { id: "ECN45K75A", name: "历史" },
    { id: "ECRI46YZQ", name: "冷门佳作" },
  ],
  ECFA5DI7Q: [
    { id: "ECFA5DI7Q", name: "近期热门" },
    { id: "ECVACWVGI", name: "高分经典" },
    { id: "ECX45ISGQ", name: "喜剧" },
    { id: "ECA45D3RQ", name: "爱情" },
    { id: "ECKI5JNJI", name: "悬疑" },
    { id: "ECME44L4Y", name: "动作" },
    { id: "ECL45GQ4I", name: "科幻" },
    { id: "EC2Y5CTPA", name: "犯罪" },
    { id: "ECMM5ALJQ", name: "惊悚" },
    { id: "ECHU473PI", name: "奇幻" },
    { id: "ECRE46B7Y", name: "恐怖" },
    { id: "ECGI5HUQI", name: "冷门佳作" },
  ],
  ECVACXBWI: [
    { id: "ECVACXBWI", name: "高分经典" },
    { id: "ECZE5BCZA", name: "喜剧" },
    { id: "ECTM5HMAI", name: "悬疑" },
    { id: "EC5I5EOCQ", name: "犯罪" },
    { id: "ECEM4373Q", name: "冷门佳作" },
  ],
  ECNA46YBA: [
    { id: "ECNA46YBA", name: "近期热门" },
    { id: "ECBQCUATA", name: "高分经典" },
    { id: "ECWM5LNJI", name: "喜剧" },
    { id: "ECEA5D2RQ", name: "爱情" },
    { id: "ECHI5FDTQ", name: "悬疑" },
    { id: "ECEA5DW5Q", name: "冷门佳作" },
  ],
  ECBE5CBEI: [
    { id: "ECBE5CBEI", name: "近期热门" },
    { id: "EC6EC5GBQ", name: "高分经典" },
    { id: "ECS45ISKI", name: "喜剧" },
    { id: "ECOU5ECZQ", name: "爱情" },
    { id: "ECZY5IDOY", name: "冷门佳作" },
  ],
  ECVM47WUA: [
    { id: "ECVM47WUA", name: "高分经典" },
    { id: "ECXI5EIII", name: "喜剧" },
    { id: "EC3Y5ISIQ", name: "爱情" },
    { id: "ECIE5FVTI", name: "古装" },
    { id: "EC3A46RGQ", name: "犯罪" },
    { id: "EC3U5ASKQ", name: "冷门佳作" },
  ],
  ECBI5EL6A: [
    { id: "ECBI5EL6A", name: "高分经典" },
    { id: "ECBU5LX3A", name: "爱情" },
    { id: "ECJQ5LAFY", name: "冷门佳作" },
  ],
  EC6I5FYHA: [
    { id: "EC6I5FYHA", name: "近期热门" },
    { id: "ECZY5KBOQ", name: "高分经典" },
    { id: "ECJQ5LPXY", name: "喜剧" },
    { id: "ECSA5KEKY", name: "爱情" },
    { id: "ECEU47F2I", name: "悬疑" },
    { id: "ECGM5NIQA", name: "犯罪" },
    { id: "ECTM5JVYA", name: "冷门佳作" },
  ],
  ECE472UNY: [
    { id: "ECE472UNY", name: "华语" },
    { id: "ECB5AE5EQ", name: "外语" },
    { id: "ECFM7Z3AA", name: "冷门佳片" },
    { id: "ECNI724YA", name: "日本" },
    { id: "EC45ABN2Y", name: "韩国" },
    { id: "ECANAAAGY", name: "喜剧" },
    { id: "ECM5AC2HQ", name: "爱情" },
    { id: "ECNA72CVA", name: "恐怖" },
    { id: "ECKU74SFA", name: "动画" },
    { id: "ECDBAETMY", name: "纪录" },
  ],
  ECBE7RX5A: [
    { id: "ECBE7RX5A", name: "华语" },
    { id: "ECBQ7RNSA", name: "外语" },
    { id: "ECSE7P7GQ", name: "冷门佳片" },
    { id: "ECRY73E2Q", name: "日本" },
    { id: "ECBM7NLJA", name: "韩国" },
    { id: "ECLE7RV6Y", name: "喜剧" },
    { id: "ECHU7QOYQ", name: "爱情" },
    { id: "ECKY7RPLQ", name: "恐怖" },
    { id: "ECZA7V7AA", name: "动画" },
    { id: "ECS47YXRQ", name: "纪录" },
  ],
  ECQ46F7XI: [
    { id: "ECQ46F7XI", name: "华语" },
    { id: "ECFA6FLWQ", name: "外语" },
    { id: "ECMY6GCCA", name: "冷门佳片" },
    { id: "ECCU6MRTY", name: "日本" },
    { id: "EC4Y6ALRA", name: "韩国" },
    { id: "ECCI6H3TA", name: "喜剧" },
    { id: "EC3A56FJA", name: "爱情" },
    { id: "ECYI6DWVQ", name: "恐怖" },
    { id: "ECHU6BXBI", name: "动画" },
    { id: "ECRM6A2JA", name: "纪录" },
  ],
  ECKA55LSA: [
    { id: "ECKA55LSA", name: "华语" },
    { id: "ECQU6DFQA", name: "外语" },
    { id: "ECSQ6DBYA", name: "冷门佳片" },
    { id: "ECEA6ANKY", name: "日本" },
    { id: "ECHM6DG7Y", name: "韩国" },
    { id: "EC4Y54ORI", name: "喜剧" },
    { id: "ECYU6IHKI", name: "爱情" },
    { id: "ECRI53OUQ", name: "恐怖" },
    { id: "EC4M6ACVQ", name: "动画" },
    { id: "ECGY527GY", name: "纪录" },
  ],
  ECWY6B2GQ: [
    { id: "ECWY6B2GQ", name: "华语" },
    { id: "ECNE54UQI", name: "外语" },
    { id: "ECRA53WMI", name: "冷门佳片" },
    { id: "ECJM6BMEA", name: "喜剧" },
    { id: "EC6A575FI", name: "爱情" },
    { id: "ECBM5YQVA", name: "恐怖" },
    { id: "ECOY6BCBI", name: "动画" },
    { id: "ECLY57EVQ", name: "纪录" },
  ],
  EC2A5MRIY: [
    { id: "EC2A5MRIY", name: "华语" },
    { id: "ECIU5HIEQ", name: "外语" },
    { id: "ECGY5FDUA", name: "冷门佳片" },
    { id: "ECCA5MMHI", name: "日本" },
    { id: "EC3A5GQ5A", name: "韩国" },
    { id: "ECM45Q7VI", name: "喜剧" },
    { id: "ECBA5UC6Q", name: "爱情" },
    { id: "EC7U5TVBY", name: "恐怖" },
    { id: "ECMY5PBHI", name: "动画" },
    { id: "EC4Q5SGKQ", name: "纪录" },
  ],
  ECFYHQBWQ: [
    { id: "ECFYHQBWQ", name: "华语" },
    { id: "ECFQHXCTQ", name: "外语" },
    { id: "ECOUHS3TY", name: "冷门佳片" },
    { id: "ECBU6ENLI", name: "喜剧" },
    { id: "ECSY52PSI", name: "爱情" },
    { id: "EC7E57OPQ", name: "动画" },
    { id: "ECYQ6G4WI", name: "纪录" },
  ],
  "2018_movie_1": [
    { id: "2018_movie_1", name: "华语" },
    { id: "2018_movie_0", name: "外语" },
    { id: "2018_movie_14", name: "冷门佳片" },
    { id: "2018_movie_5", name: "日本" },
    { id: "2018_movie_4", name: "韩国" },
    { id: "2018_movie_16", name: "喜剧" },
    { id: "2018_movie_17", name: "爱情" },
    { id: "2018_movie_19", name: "恐怖" },
    { id: "2018_movie_20", name: "动画" },
    { id: "2018_movie_21", name: "纪录" },
  ],
  "2017_movie_chinese_score": [
    { id: "2017_movie_chinese_score", name: "华语" },
    { id: "2017_movie_foreign_score", name: "外语" },
    { id: "2017_movie_dark_horse", name: "冷门佳片" },
    { id: "2017_movie_696", name: "日本" },
    { id: "2017_movie_695", name: "韩国" },
    { id: "2017_movie_699", name: "喜剧" },
    { id: "2017_movie_700", name: "爱情" },
    { id: "2017_movie_702", name: "恐怖" },
    { id: "2017_movie_686", name: "纪录" },
  ],
  "2016_movie_451": [
    { id: "2016_movie_451", name: "华语" },
    { id: "2016_movie_272", name: "外语" },
    { id: "2016_movie_456", name: "冷门佳片" },
    { id: "2016_movie_459", name: "日本" },
    { id: "2016_movie_458", name: "韩国" },
    { id: "2016_movie_465", name: "喜剧" },
    { id: "2016_movie_466", name: "爱情" },
    { id: "2016_movie_468", name: "恐怖" },
    { id: "2016_movie_469", name: "动画" },
    { id: "2016_movie_470", name: "纪录" },
  ],
  "2015_movie_3": [
    { id: "2015_movie_3", name: "华语" },
    { id: "2015_movie_2", name: "外语" },
    { id: "2015_movie_43", name: "冷门佳片" },
    { id: "2015_movie_45", name: "日本" },
    { id: "2015_movie_44", name: "韩国" },
    { id: "2015_movie_54", name: "动画" },
    { id: "2015_movie_55", name: "纪录" },
  ],
  "2014_movie_2": [
    { id: "2014_movie_2", name: "华语" },
    { id: "2014_movie_1", name: "外语" },
    { id: "2014_movie_5", name: "冷门佳片" },
    { id: "2014_movie_7", name: "日本" },
    { id: "2014_movie_6", name: "韩国" },
    { id: "2014_movie_9", name: "动画" },
    { id: "2014_movie_10", name: "纪录" },
  ],
  EC2FACYKQ: [
    { id: "EC2FACYKQ", name: "华语剧集" },
    { id: "ECHNAB4LY", name: "英美新剧" },
    { id: "ECWQ7ZJGY", name: "英美续订" },
    { id: "ECPNAHZ2A", name: "日本剧集" },
    { id: "EC7VAFY4Q", name: "韩国剧集" },
    { id: "EC647Z33A", name: "综艺" },
    { id: "ECQM7YUOQ", name: "动画" },
    { id: "ECIM7ZJCI", name: "纪录" },
    { id: "EC2RAB7MY", name: "微短剧" },
  ],
  ECYA7RAZQ: [
    { id: "ECYA7RAZQ", name: "华语剧集" },
    { id: "EC5U7O7WY", name: "英美新剧" },
    { id: "ECOY7WR4I", name: "英美续订" },
    { id: "ECRE7PJSQ", name: "日本剧集" },
    { id: "ECMM7RKRA", name: "韩国剧集" },
    { id: "ECTE7TV3Y", name: "综艺" },
    { id: "ECHQ7SAPY", name: "动画" },
    { id: "ECDM74KXY", name: "纪录" },
  ],
  ECTE6EOZA: [
    { id: "ECTE6EOZA", name: "华语剧集" },
    { id: "ECUI6CVAI", name: "英美新剧" },
    { id: "ECM46I42A", name: "英美续订" },
    { id: "ECPE6B6NI", name: "日本剧集" },
    { id: "EC246FT6Y", name: "韩国剧集" },
    { id: "EC7I6GR6A", name: "综艺" },
    { id: "EC3Q6JTOQ", name: "动画" },
    { id: "ECCU6NNCI", name: "纪录" },
  ],
  ECWU56XUI: [
    { id: "ECWU56XUI", name: "华语剧集" },
    { id: "ECQY6HRQQ", name: "英美新剧" },
    { id: "ECMU6H5VY", name: "英美续订" },
    { id: "ECRY6I6FA", name: "日本剧集" },
    { id: "EC2Y6BEGQ", name: "韩国剧集" },
    { id: "EC4U6BXLA", name: "综艺" },
    { id: "ECRI533KQ", name: "动画" },
    { id: "ECR455GTQ", name: "纪录" },
  ],
  ECOY56I6Y: [
    { id: "ECOY56I6Y", name: "华语剧集" },
    { id: "EC5U5X5FA", name: "英美新剧" },
    { id: "ECEI6A5ZI", name: "英美续订" },
    { id: "ECZQ6AD6Y", name: "日本剧集" },
    { id: "ECNI5ZBSQ", name: "韩国剧集" },
    { id: "ECGA6CUPA", name: "动画" },
    { id: "ECPY52QZY", name: "纪录" },
  ],
  ECCM5TXSI: [
    { id: "ECCM5TXSI", name: "华语剧集" },
    { id: "ECSA5PTFI", name: "英美新剧" },
    { id: "ECZU5SJAI", name: "英美续订" },
    { id: "ECBI5KPKY", name: "日本剧集" },
    { id: "ECJM5OL6Y", name: "韩国剧集" },
  ],
  ECR4HOW3I: [
    { id: "ECR4HOW3I", name: "华语剧集" },
    { id: "ECS4HX5JI", name: "英美新剧" },
    { id: "ECS4HX6GQ", name: "英美续订" },
    { id: "EC2AHUXEA", name: "日本剧集" },
    { id: "ECR4HO7JA", name: "韩国剧集" },
  ],
  "2018_tv_23": [
    { id: "2018_tv_23", name: "华语剧集" },
    { id: "2018_tv_24", name: "英美新剧" },
    { id: "2018_tv_25", name: "英美续订" },
    { id: "2018_tv_26", name: "日本剧集" },
    { id: "2018_tv_27", name: "韩国剧集" },
    { id: "2018_tv_28", name: "动画" },
    { id: "2018_tv_29", name: "纪录" },
  ],
  "2017_tv_domestic_score": [
    { id: "2017_tv_domestic_score", name: "华语剧集" },
    { id: "2017_tv_american_score", name: "英美新剧" },
    { id: "2017_tv_743", name: "英美续订" },
    { id: "2017_tv_740", name: "日本剧集" },
    { id: "2017_tv_741", name: "韩国剧集" },
    { id: "2017_tv_706", name: "动画" },
    { id: "2017_tv_707", name: "纪录" },
  ],
  "2016_tv_478": [
    { id: "2016_tv_478", name: "华语剧集" },
    { id: "2016_tv_472", name: "英美新剧" },
    { id: "2016_tv_474", name: "英美续订" },
    { id: "2016_tv_482", name: "日本剧集" },
    { id: "2016_tv_481", name: "韩国剧集" },
    { id: "2016_tv_486", name: "动画" },
    { id: "2016_tv_487", name: "纪录" },
  ],
  "2015_tv_6": [
    { id: "2015_tv_6", name: "华语剧集" },
    { id: "2015_tv_7", name: "英美新剧" },
    { id: "2015_tv_13", name: "英美续订" },
    { id: "2015_tv_14", name: "日本剧集" },
    { id: "2015_tv_15", name: "韩国剧集" },
    { id: "2015_tv_60", name: "动画" },
  ],
  "2014_tv_14": [
    { id: "2014_tv_14", name: "华语剧集" },
    { id: "2014_tv_13", name: "英美新剧" },
    { id: "2014_tv_12", name: "英美续订" },
    { id: "2014_tv_16", name: "日本剧集" },
    { id: "2014_tv_15", name: "韩国剧集" },
  ],
} as const;
